# Site settings
title: IT Support - Computer Installation
email: kenbrezinski@live.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Professional tutoring services in Vancouver, BC. Specializing in computer skills, IT support, and personalized learning for all ages. Achieve your academic and technical goals with expert guidance."
keywords: "tutoring, computer skills, IT support, Vancouver, academic help, technology lessons, personalized learning, education, study support, online tutoring"
skills: "PC Repairs and Installations - Computer Backup - Cloud Storage and Password Manager"
meta_author: Brezinski Kenneth

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2E86C1 # Professional Blue
  primary-rgb: "46,134,193"
  secondary: F4D03F # Gold Accent
  secondary-dark: 283747 # Deep Navy

# Footer settings
footer:
  copyright: Kenneth Brezinski
  location:
  social:
  credits:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/kenneth-brezinski-b65a05136/

# Postal address (add as many lines as necessary)
address:
  - line: Vancouver, British-Columbia
  - line: 

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
